services:

  traefik:
    image: traefik:v3.4
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Optional: Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  db:
    image: mariadb
    restart: always
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  account:
    container_name: account
    build:
      context: src
      dockerfile: account/dockerfile
    environment:
      - CONTEXT_PATH=${USER_PATH}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account.rule=PathPrefix(`$USER_PATH`)"
      - "traefik.http.routers.account.entrypoints=web"
      - "traefik.http.services.account.loadbalancer.server.port=8080"
    ports:
      - "8081:8080"
    depends_on:
      - db
  
  shop:
    container_name: shop
    build:
      context: src
      dockerfile: shop/dockerfile
    environment:
      - CONTEXT_PATH=${SHOP_PATH}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shop.rule=PathPrefix(`$SHOP_PATH`)"
      - "traefik.http.routers.shop.entrypoints=web"
      - "traefik.http.services.shop.loadbalancer.server.port=8080"
    ports:
      - "8082:8080"
    depends_on:
      - db

  order:
    container_name: order
    build:
      context: src
      dockerfile: order/dockerfile
    environment:
    - CONTEXT_PATH=${ORDER_PATH}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.order.rule=PathPrefix(`$ORDER_PATH`)"
      - "traefik.http.routers.order.entrypoints=web"
      - "traefik.http.services.order.loadbalancer.server.port=8080"
    ports:
      - "8083:8080"
    depends_on:
      - db
  
  payment:
    container_name: payment
    build:
      context: src
      dockerfile: payment/dockerfile
    environment:
    - CONTEXT_PATH=${PAYMENT_PATH}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment.rule=PathPrefix(`$PAYMENT_PATH`)"
      - "traefik.http.routers.payment.entrypoints=web"
      - "traefik.http.services.payment.loadbalancer.server.port=8080"
    ports:
      - "8084:8080"
    depends_on:
      - db