services:
  db:
    image: mariadb
    restart: always
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  account:
    container_name: account
    build:
      context: src
      dockerfile: account/dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db
  
  shop:
    container_name: shop
    build:
      context: src
      dockerfile: shop/dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - db